### ISSUE TITLE
Little mistake on updateCriteria method

### ISSUE THREAD

**Issue by rcluan** [shripalsoni04/nativescript-geofire-plugin#1]
Hello there, mate! I was checking the code of your plugin and I've found something I think is not right. Could you confirm it?

I believe this
```
    if (criteria.radius) {
      this.query.setCenter(criteria.radius);
    }
```
should be something like this
```
    if (criteria.radius) {
      this.query.setRadius(criteria.radius);
    }
```
shouldn't it?

This happened on line 128 of your nativescript-geofire.android.ts, I haven't checked the ios file though.

Cheers.

**Comment by shripalsoni04** [comment]
Thanks @rcluan .

You are right. There was mistake in setting radius in `updateCriteria` function for Android. For iOS it is correct.

I have resolved this and fix is available at version 1.0.5.
