### ISSUE TITLE
Webpack build fails due to package.json entry

### ISSUE THREAD

**Issue by kilka** [shripalsoni04/nativescript-geofire-plugin#2]
This plugin causes webpack builds to fail because it cannot find the plugin. This can be resolved by removing the ".js" from the package name in package.json

Change "main": "nativescript-geofire.js",
To         "main": "nativescript-geofire",

Relevant section from the Nativescript site:

http://docs.nativescript.org/angular/tooling/bundling-with-webpack.html#recommendations-for-plugin-authors

**Comment by shripalsoni04** [comment]
Thanks @kilka for reporting this issue.

I have resolved it and the fix is available at **1.0.5**.
