### ISSUE TITLE
Geofire not compatible with 4.xx Firebase

### ISSUE THREAD

**Issue by kilka** [shripalsoni04/nativescript-geofire-plugin#3]
New version of nativescript-firebase has moved to the 4.xx version of Firebase.

Looks like for IOS the geofire plugin works fine just by changing the commit in the podspec to use "96d6463f59016785f9c5ae9b669019c44786a23f". Not sure if any changes need to be made for Android.

**Comment by sagearbor** [comment]
Thanks for that Kilka.  For ease, below is how I followed your suggestion to fix

> tns plugin remove nativescript-geofire-plugin
       (just incase you messed up trying to fix)
> tns platform remove ios
> tns plugin add nativescript-geofire-plugin
> vi node_modules/nativescript-geofire-plugin/platforms/ios/Podfile
comment out current line and add new line as shown below

#pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git', :commit => 'dbb8d193f5ee1371837800d0502bd29cba779da4'
pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git', :commit => '96d6463f59016785f9c5ae9b669019c44786a23f'

> tns run ios

**Comment by shripalsoni04** [comment]
Thanks @kilka and @sagearbor for reporting bug and finding solution.

Version 2.0.0 of nativescript-geofire-plugin is published which is compatible with Firebase 4.x.
